### ISSUE TITLE
Dependency Injection Container

### ISSUE THREAD

**Issue by praswicaksono** [kecik-framework/kecik#1]
apakah ada rencana untuk menambahkan fitur ini?

**Comment by dnaextrim** [comment]
bisa dijelaskan terlebih dahulu mengenai fitur tersebut, soalnya saya baru denger fitur tersebut, dan jika memang bisa saya buat akan saya buat

Thanks...

**Comment by praswicaksono** [comment]
fitur ini bertujuan untuk mengelola dependency anda, contoh dependency injection container yang paling simple adalah http://pimple.sensiolabs.org/ mungkin ini bisa anda integrasikan ke framework anda.

**Comment by dnaextrim** [comment]
Terima kasih atas penjelasannya, saya akan coba pelajari dulu. Dan insyallah akan saya realisasikan fitur ini.

:D

**Comment by praswicaksono** [comment]
dengan fitur ini Object controller bisa di buat lazy load, jadi pada saat bootstrapping ga semua object controller yang diload

**Comment by dnaextrim** [comment]
iya mas, ini lagi dipikirkan caranya. :smile:

**Comment by praswicaksono** [comment]
sebenernya caranya cukup mudah kok, kalo pake irc gabung ke #phpmentoring @ freenode bisa diskusi bareng disana. nick saya Jowy disana.

**Comment by dnaextrim** [comment]
Saya install dulu program mirc nya mas, saya baru nyoba buat DIC seperti pimple, sudah sampai tahap factory. Saya buat jadi library/pustaka jadi terpisah dari system Kecik Framework, cara penggunaan sama seperti cara penggunaan pimple

**Comment by praswicaksono** [comment]
harusnya DIC jadi satu sama framework core nya mas, sama seperti silex dan slim. Untuk selanjutnya lanjur di IRC aja mas

**Comment by dnaextrim** [comment]
Library/Pustaka DIC untuk kecik framework sudah rilis, dengan mengupdate kecik framework yang baru, sekarang pustaka/library DIC akan terintegrasi secara otomatis kedalam kecik framework jika pustaka/library dic terinstall

**Comment by praswicaksono** [comment]
mantab :+1:
